# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: DigidWorks
title: Business Software
email: hi@digidworks.com
description: >- # this means to ignore newlines until "baseurl:"
  DigidWorks provides application development services. We bring software and tech solutions to your business!
display_site_title_char_limit: 20
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://digidworks.com" # the base hostname & protocol for your site, e.g. http://example.com

logo_social: "/assets/img/digid-works-logo-2x1.png"

logo_svg: "/assets/img/digid-works-logo.svg"
logo_small_svg: "/assets/img/digid-works-logo-small.svg"
logo_small_bw_svg: "/assets/img/digid-works-logo-small-bw.svg"
twitter_handle: "@th3_mad_hatter"
timezone: Europe/Sofia
permalink: /:title

# Build settings
markdown: kramdown
# theme: minima

plugins:
  - jekyll-paginate-v2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  portfolio:
    output: true

defaults:
  - scope:
      path: "post"
    values:
      layout: "redirect"
  - scope:
      path: "project"
    values:
      layout: "redirect-to-product"
  - scope:
      path: "portfolio"
    values:
      layout: "redirect-to-product"
  - scope:
      path: "portfolio"
      type: "pages"
    values:
      layout: "redirect-to-product"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "redirect-to-product"
      permalink: /:title
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:title
  - scope:
      path: ""
    values:
      layout: "default"

pagination:
  enabled: true
  title: ':title | Page :num'
